core/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('user.urls')),
    path('trade/', include('trade.urls')),
    path('draw/', include('draw.urls')),
    path('invoice/', include('invoice.urls')),
    path('lottery/', include('lottery.urls')),
    path(settings.ADMIN_URL +'/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

invoice/models.py
from django.db import models
from django.conf import settings
from django.core.validators import MaxValueValidator
from user.models import User
from lottery.models import BettingAgency

from datetime import datetime
import pytz

from decimal import Decimal

# Create your models here.
class Commission(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    percent = models.PositiveSmallIntegerField('Commission percentage', 
        validators=[MaxValueValidator(settings.MAX_COMMISSION_PERCENT)], default=0)
    sales_record = models.PositiveIntegerField('Sales record', default=2147483647)
    start_period = models.DateField(default=datetime.min.date())
    end_period = models.DateField(default=datetime.max.date())
    #
    timestamp = models.DateTimeField(auto_now_add=True)
    #
    class Meta:
        db_table = 'commission'
    #
    def __str__(self): return '%s - Commission: %s%%' % (self.user.get_full_name(), self.percent)
    #
#
class Invoice(models.Model):
    betting_agency = models.ForeignKey(BettingAgency, on_delete=models.CASCADE)
    system_commission = models.PositiveSmallIntegerField('System Commission Percentage', default=0)
    was_paid = models.BooleanField('Was paid', default=False)
    #
    timestamp = models.DateTimeField(auto_now_add=True)
    #
    class Meta:
        db_table = 'invoice'
    #
    def get_total_sales(self):
        total_sales = Decimal('0.00')
        for row in self.rowinvoice_set.all():
            total_sales += row.total_sales
        return total_sales
    #
    def get_total_earnings(self):
        total_earning = Decimal('0.00')
        for row in self.rowinvoice_set.all():
            total_earning += row.total_sales - row.total_rewards - row.total_commission
        return total_earning
    #
    def get_total_to_pay_to_manager(self):
        _total = self.get_total_earnings() * Decimal(self.system_commission / 100)
        return _total if _total > Decimal('0.00') else Decimal('0.00')
    #
    def __str__(self):
        return '%s - Fecha: %s' % (
            self.betting_agency,
            self.timestamp.astimezone(pytz.timezone(settings.TIME_ZONE)).strftime('%d/%m/%Y - %I:%M %p')
        )
#
class RowInvoice(models.Model):
    invoice = models.ForeignKey(Invoice, on_delete=models.CASCADE)
    #
    total_sales = models.DecimalField('Total sales', max_digits=6, decimal_places=2, default=0)
    total_rewards = models.DecimalField('Total sales', max_digits=6, decimal_places=2, default=0)
    total_rewards_to_pay = models.DecimalField('Total sales', max_digits=6, decimal_places=2, default=0)
    total_commission = models.DecimalField('Total commission', max_digits=6, decimal_places=2, default=0)
    #
    timestamp = models.DateTimeField(auto_now_add=True)
    #
    class Meta:
        db_table = 'row_invoice'
        verbose_name = 'Row Invoice'
    #
    def get_ticket_user_fullname(self): return self.ticket_set.last().user.get_full_name()
#

lottery/models.py
from django.db import models
from django.conf import settings

# Create your models here.
class Lottery(models.Model):
    name = models.CharField('Name of lottery', max_length=150)
    picture = models.ImageField('Logo', upload_to='lottery', null=True, blank=True)
    #
    timestamp = models.DateTimeField(auto_now_add=True)
    #
    class Meta:
        db_table = 'lottery'
    #
    def __str__(self): return self.name
#
class Schedule(models.Model):
    DAYS = (
        ('0', 'Lunes'),
        ('1', 'Martes'),
        ('2', 'Miercoles'),
        ('3', 'Jueves'),
        ('4', 'Viernes'),
        ('5', 'Sábado'),
        ('6', 'Domingo'),
    )
    #
    lottery = models.ForeignKey(Lottery, on_delete=models.CASCADE)
    day = models.CharField('Day', max_length=1, choices=DAYS)
    turn = models.TimeField('Draw schedule')
    #
    timestamp = models.DateTimeField(auto_now_add=True)
    #
    class Meta:
        unique_together = ('lottery', 'day', 'turn',)
        db_table = 'schedule'
    #
    def __str__(self):
        return '%s - %s - %s' % (self.lottery, self.DAYS[int(self.day)][1], self.turn)
#
class BettingAgency(models.Model):
    name = models.CharField('Name of betting agency', max_length=150)
    tax_id = models.CharField('Tax Identification Number', max_length=15)
    description = models.CharField('Betting agency description', max_length=512, null=True, blank=True)
    currency = models.CharField('Currency', max_length=2, choices=[(str(i), settings.CURRENCY[i]) for i in range(0, len(settings.CURRENCY))])
    minimum_bet = models.PositiveIntegerField('Minimum bet')
    system_commission = models.PositiveSmallIntegerField('System Commission Percentage', default=0)
    is_active = models.BooleanField('Can be operated', default=True)
    #
    timestamp = models.DateTimeField(auto_now_add=True)
    #
    class Meta:
        db_table = 'betting_agency'
        verbose_name = 'Betting Agency'
    #
    def get_lotteries(self):
        lotteries = self.pattern_set.values_list('lottery', flat=True).distinct()
        return Lottery.objects.filter(pk__in=lotteries)
    #
    def __str__(self): return self.name
#
class Icon(models.Model):
    name = models.CharField('Name of icon', max_length=150)
    identifier = models.PositiveIntegerField('Numeric Identifier')
    picture = models.ImageField('Logo', upload_to='icon', null=True, blank=True)
    #
    timestamp = models.DateTimeField(auto_now_add=True)
    #
    class Meta:
        db_table = 'icon'
    #
    def __str__(self): return '%d - %s' % (self.identifier, self.name)
#
class Pattern(models.Model):
    betting_agency = models.ForeignKey(BettingAgency, on_delete=models.CASCADE)
    lottery = models.ForeignKey(Lottery, on_delete=models.CASCADE)
    icon = models.ForeignKey(Icon, on_delete=models.CASCADE)
    bet_multiplier = models.PositiveIntegerField('Bet multiplier')
    minimum_bet = models.PositiveIntegerField('Minimum bet')
    is_active = models.BooleanField('Can be included in draws', default=True)
    #
    timestamp = models.DateTimeField(auto_now_add=True)
    #
    class Meta:
        unique_together = ('betting_agency', 'lottery', 'icon',)
        db_table = 'pattern'
    #
    def __str__(self):
        return '%s - %s - %s' % (self.betting_agency, self.lottery, self.icon)

trade/models.py
from django.db import models
from lottery.models import Icon
from draw.models import Draw, DrawResult
from user.models import User
from invoice.models import RowInvoice

from django.conf import settings
from django.core.validators import MaxValueValidator

from decimal import Decimal
import uuid

# Create your models here.
class Ticket(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    client = models.PositiveIntegerField('DNI', null=True, blank=True)
    uuid = models.UUIDField(default=uuid.uuid4, unique=True, editable=False)
    was_printed = models.BooleanField('Print control', default=False)
    is_invalidated = models.BooleanField('Invalidation control', default=False)
    #
    user_commission_percent = models.PositiveSmallIntegerField('Commission percentage', 
        validators=[MaxValueValidator(settings.MAX_COMMISSION_PERCENT)], default=0)
    row_invoice = models.ForeignKey(RowInvoice, on_delete=models.SET_NULL, null=True, blank=True)
    #
    timestamp = models.DateTimeField(auto_now_add=True)
    #
    class Meta:
        db_table = 'ticket'
    #
    def has_pending_draws(self):
        if self.rowticket_set.exists():
            for row in self.rowticket_set.all():
                if not row.draw.drawresult_set.exists():
                    return True
        return False

    #
    def get_total_bet_amount(self):
        t_amount = Decimal('0.00')
        if self.rowticket_set.exists():
            for row in self.rowticket_set.all():
                t_amount += row.bet_amount
        return t_amount
    #
    def get_total_reward(self):
        t_reward = Decimal('0.00')
        if self.rowticket_set.exists():
            for row in self.rowticket_set.all():
                if row.is_a_winning_row() or row.was_rewarded:
                    t_reward += row.bet_amount_to_pay()
        return t_reward
    #
    def get_total_reward_pending_to_pay(self):
        t_pending_reward = Decimal('0.00')
        if self.rowticket_set.exists():
            for row in self.rowticket_set.all():
                if row.is_a_winning_row():
                    t_pending_reward += row.bet_amount_to_pay()
        return t_pending_reward
    #
    def get_lottery(self): return self.rowticket_set.last().draw.schedule.lottery
    #
    def get_readable_uuid(self): return str(self.uuid.int)[-10:]
    #
    def get_client_or_notapply(self): return self.client if self.client else settings.NOT_APPLY_LABEL
    #
    def __str__(self): return 'Ticket Nº %d - UUID Readable: #%s' % (self.pk, self.get_readable_uuid())
#
class RowTicket(models.Model):
    ticket = models.ForeignKey(Ticket, on_delete=models.CASCADE)
    draw = models.ForeignKey(Draw, on_delete=models.CASCADE)
    icon = models.ForeignKey(Icon, on_delete=models.CASCADE)
    bet_multiplier = models.PositiveIntegerField('Bet multiplier')
    bet_amount = models.DecimalField('Bet amount', max_digits=6, decimal_places=2)
    was_rewarded = models.BooleanField('Was rewarded', default=False)
    payment = models.DateTimeField('Payment timestamp', null=True, blank=True)
    #
    timestamp = models.DateTimeField(auto_now_add=True)
    #
    class Meta:
        db_table = 'row_ticket'
        verbose_name = 'Row Ticket'
    #
    def bet_amount_to_pay(self): return self.bet_amount *self.bet_multiplier
    #
    def is_a_winning_row(self): return self.winningticket_set.exists()
    #
    def __str__(self): return '%s - %s - %s' % (self.ticket, self.draw, self.icon.name) 
#
class WinningTicket(models.Model):
    row_ticket = models.ForeignKey(RowTicket, on_delete=models.CASCADE)
    draw_result = models.ForeignKey(DrawResult, on_delete=models.CASCADE)
    uuid_ticket = models.CharField('Readable uuid of ticket', max_length=10, editable=False)
    #
    class Meta:
        db_table = 'winning_ticket'
        verbose_name = 'Winning Ticket'
    #
    def __str__(self): return '%s' % (self.row_ticket)

user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from lottery.models import BettingAgency

# Create your models here.

class User(AbstractUser):
    banker = models.ForeignKey('self', on_delete=models.RESTRICT, null=True, blank=True)
    betting_agency = models.ForeignKey(BettingAgency, on_delete=models.CASCADE, null=True, blank=True)
    is_banker = models.BooleanField('Can create sellers', default=False)
    is_betting_agency_staff = models.BooleanField('Can register a lottery result', default=False)
    #
    is_system_manager = models.BooleanField('Lottery System Administrator', default=False)
    #
    class Meta:
        db_table = 'user'
    #
    def get_full_name(self): return '%s %s' % (self.first_name, self.last_name)
    #
    def clean(self):
        self.username = self.username.lower()
        self.first_name = self.first_name.title()
        self.last_name = self.last_name.title()
        return super().clean()

templates/base.html
<!doctype html>
<html lang="es">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <!-- Bootstrap CSS & Icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet"
            integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css">

        <script src="https://code.jquery.com/jquery-3.6.1.min.js"
            integrity="sha256-o88AwQnZB+VDvE9tvIXrMQaPlFFSUTR+nldQm1LuPXQ="
            crossorigin="anonymous">
        </script>
        
        {% load static %}

        <style>
            body { background-image: linear-gradient(180deg, #eee, #fff 100px, #fff) no-repeat fixed; }
            #to_print { display: none; }
            @media print {
                header, main { display: none; }
                #to_print {
                    display: block; width: 100% !important; padding: 0 !important; margin: 0 !important;
                }
            }
            ::-webkit-scrollbar { display: none; }
        </style>

        <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}" />

        <title>{{ page_title }}Sistema de Lotería</title>
    </head>
    <body class="container py-3" style="max-width: 768px;">

        {% include "header.html" %}
        {% block main %}<!-- default content-->{% endblock %}
        
        {# include "to_print.html" #}
        
        {% if ticket_imagen %}
            <div id="to_print">
                <img src="data:image/png;base64,{{ ticket_imagen }}">
            </div>
        {% endif %}

        <!-- Bootstrap Bundle with Popper -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4"
            crossorigin="anonymous">
        </script>
        <script>
            $(document).ready(function() {
                setTimeout(function() {
                    $('#modal_message').modal('toggle')
                }, 200);
            });
        </script>
    </body>
</html>

templates/create_seller.html
{% extends "main.html" %}

{% block content %}

<div class="justify-content-center py-3">
    <div class="text-center">
        <form action="" method="post">
            {% csrf_token %}
            <h1 class="h2 mb-3 fw-normal">Registrar Vendedor</h1>
            <div class="form-floating mb-2">
                <input type="text" class="form-control" name="username" id="id_username" autocapitalize="none" autocomplete="username" maxlength="150" required placeholder="Nombre de Usuario">
                <label for="id_username">Nombre de Usuario</label>
            </div>
            <div class="text-start text-muted mb-4">
                <span class="helptext">Requerido. Solo letras, dígitos y @/./+/-/_.</span>
            </div>

            <div class="form-floating mt-4 mb-2">
                <input type="text" class="form-control" name="first_name" id="id_first_name" maxlength="150" required placeholder="Nombre">
                <label for="id_first_name">Nombre</label>
            </div>
            <div class="form-floating mb-4">
                <input type="text" class="form-control" name="last_name" id="id_last_name" maxlength="150" required placeholder="Apellido">
                <label for="id_last_name">Apellido</label>
            </div>

            <div class="text-start text-muted mb-4">
                <span class="helptext">
                    <span>Su contraseña...</span>
                    <ul>
                        <li>No puede ser similar a su otra información personal.</li>
                        <li>Debe contener al menos 8 caracteres.</li>
                        <li>No puede ser una contraseña de uso común.</li>
                        <li>No puede ser completamente numérica.</li>
                    </ul>
                </span>
            </div>

            <div class="form-floating mb-2">
                <input type="password" class="form-control" name="password1" id="id_password1" autocomplete="new-password" maxlength="128" required placeholder="Contraseña">
                <label for="id_password1">Contraseña</label>
            </div>
            <div class="form-floating mb-4">
                <input type="password" class="form-control" name="password2" id="id_password2" autocomplete="new-password" maxlength="128" required placeholder="Confimación de Contraseña">
                <label for="id_password2">Confirmación de Contraseña</label>
            </div>
            <div class="text-start text-muted mb-2">
                <span class="helptext">Cada vendedor posee un porcentaje de comisión ajustable, el valor maximo es de {{ MAX_COMMISSION_PERCENT }}.</span>
            </div>
            <div class="input-group mb-4">
                <div class="form-floating">
                    <input type="number" class="form-control" id="id_percent" name="percent" placeholder="Porcentaje de Comisión" min="0" max="{{ MAX_COMMISSION_PERCENT }}" value="{{ seller.commission_set.last.percent }}" required>
                    <label for="id_percent">Ingresa el porcentaje de comisión</label>
                </div>
                <span class="input-group-text">&nbsp%&nbsp</span>
            </div>
            <div class="d-grid gap-2 d-flex justify-content-end">
                <a href="{% url 'list_seller' %}" class="btn btn-lg btn-outline-danger">Cancelar</a>
                <button class="btn btn-lg btn-outline-primary" type="submit">Registrar Vendedor</button>
            </div>
        </form>
    </div>
</div>

{% endblock %}

templates/edit_seller.html
{% extends "main.html" %}

{% block content %}

<div class="justify-content-center py-3">
    <div class="text-center">
        <form action="" method="post">
            {% csrf_token %}
            <h1 class="h2 mb-3 fw-normal">Actualizar Vendedor</h1>
            <div class="form-floating mb-2">
                <input type="text" class="form-control" name="username" value="{{ form.username.value }}" id="id_username" autocapitalize="none" autocomplete="username" maxlength="150" required placeholder="Nombre de Usuario" {% if form.username.value == request.user.username %} readonly {% endif %}>
                <label for="id_username">Nombre de Usuario</label>
            </div>
            <div class="text-start text-muted mb-4">
                <span class="helptext">Requerido. Solo letras, dígitos y @/./+/-/_.</span>
            </div>
            <div class="text-start text-muted mb-4">
                {% if form.username.value == request.user.username %}
                <span>No puedes resetear la contraseña desde este formulario. Pero si la puedes cambiar al presionar <a href="{% url 'password_change' %}">aquí</a>.</span>
                {% else %}
                <span>Si el vendedor ha olvidado la contraseña, puede presionar 
                    <a href="{% url 'reset_password' seller.pk %}">aquí</a> para restaurar la misma a: <i>{{ DEFAULT_PASSWORD }}</i>
                </span>
                {% endif %}
            </div>
            <div class="form-floating mt-4 mb-2">
                <input type="text" class="form-control" name="first_name" value="{{ form.first_name.value }}" id="id_first_name" maxlength="150" required placeholder="Nombre">
                <label for="id_first_name">Nombre</label>
            </div>
            <div class="form-floating mb-4">
                <input type="text" class="form-control" name="last_name" value="{{ form.last_name.value }}" id="id_last_name" maxlength="150" required placeholder="Apellido">
                <label for="id_last_name">Apellido</label>
            </div>

            <div class="text-start text-muted mb-2">
                <span class="helptext">Cada vendedor posee un porcentaje de comisión ajustable, el valor maximo es de {{ MAX_COMMISSION_PERCENT }}.</span>
            </div>
            <div class="input-group mb-4">
                <div class="form-floating">
                    <input type="number" class="form-control" id="id_percent" name="percent" placeholder="Porcentaje de Comisión" min="0" max="{{ MAX_COMMISSION_PERCENT }}" value="{{ seller.commission_set.last.percent }}" required>
                    <label for="id_percent">Ingresa el porcentaje de comisión</label>
                </div>
                <span class="input-group-text">&nbsp%&nbsp</span>
            </div>

            <div class="form-check form-switch text-start mb-2">
                <input type="checkbox" class="form-check-input" name="is_active" id="id_is_active" {% if form.is_active.value %} checked {% endif %} {% if form.username.value == request.user.username %} disabled {% endif %}>
                <label class="form-check-label" for="id_is_active">Casilla de estado Activo/Suspendido</label>
            </div>
            <div class="text-start text-muted mb-4">
                <span class="helptext">Designa si este usuario debe ser tratado como un vendedor activo. Anule la selección de esto en lugar de eliminar la cuenta.</span>
            </div>
            <div class="d-grid gap-2 d-flex justify-content-end">
                <a href="{% url 'list_seller' %}" class="btn btn-lg btn-outline-danger">Cancelar</a>
                <button class="btn btn-lg btn-outline-primary" type="submit">Guardar Cambios</button>
            </div>
        </form>
    </div>
</div>

{% endblock %}

templates/sell_ticket.html
{% extends "main.html" %}

{% block content %}

<div class="justify-content-center py-3">
    <div class="text-center">
        <form action="{% url 'sell_ticket' lottery.pk %}" method="post">
            {% csrf_token %}
            <h1 class="h2 mb-3 fw-normal">Vender Ticket</h1>
            <h2 class="fs-4 mb-3 text-muted">{{ lottery }}</h2>
            <div class="form-floating mb-2">
                <input type="number" class="form-control" name="client" id="id_client" min="1" max="2147483647" autofocus placeholder="Documento de identificación">
                <label for="id_client">Documento de Identificación</label>
            </div>
            <div class="text-start text-muted mb-4">
                <span class="helptext">Solo dígitos. Es un producto solo para mayores de edad.</span>
            </div>
            <div class="overflow-auto">
                <div style="width: 576px;">
                    <div id="row_ticket" class="row g-2 mb-2">
                        <div class="col-4">
                            <div class="form-floating">
                                <select class="form-select" name="draw_list" required id="id_draw_selection">
                                    <option  value="" selected="selected">Seleccione...</option>
                                    {% for draw in draw_list %}
                                        <option value="{{ draw.pk }}">{{ draw.schedule.turn|date:'h:i A' }}</option>
                                        {% empty %}
                                            <option selected="selected">Sin Sorteos</option>
                                    {% endfor %}
                                </select>
                                <label class="" for="id_draw_selection">Hora del sorteo</label>
                            </div>
                        </div>
                        <div class="col-4">
                            <div class="form-floating">
                                <select class="form-select" name="pattern_list" required id="id_pattern_selection">
                                    <option  value="" selected="selected">Seleccione...</option>
                                    {% for pattern_row in pattern_list %}
                                        <option value="{{ pattern_row.pk }}">{{ pattern_row.icon }}</option>
                                    {% endfor %}
                                </select>
                                <label class="" for="id_pattern_selection">Ficha</label>
                            </div>
                        </div>
                        <div class="col-3">
                            <div class="input-group">
                                <span class="input-group-text">{{ request.user.betting_agency.get_currency_display }}</span>
                                <div class="form-floating">
                                    <input type="number" class="form-control" name="bet_amount_list" id="id_bet_amount" min="{{ request.user.betting_agency.minimum_bet }}" step=".01" required placeholder="Monto de la apuesta">                            
                                    <label for="id_bet_amount">Monto</label>
                                </div>
                            </div>
                        </div>
                        <div class="col-1">
                            <button id="remove_row" type="button" class="btn mt-2">
                                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-x-circle text-danger" viewBox="0 0 16 16">
                                    <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
                                    <path d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z"/>
                                </svg>
                            </button>
                        </div>
                    </div>
                    <div id="new_row"></div>
                </div>
            </div>
            <div class="text-end mt-3 mb-4">
                <span class="text-muted">
                    Para agregar una nueva fila presione
                    <a id="add_row" type="button" class="text-decoration-none">aquí</a>
                </span>
            </div>
            <div class="d-grid gap-2 d-flex justify-content-end">
                <a href="{% url 'index' %}" class="btn btn-lg btn-outline-danger">Cancelar</a>
                <button class="btn btn-lg btn-outline-success" type="submit">Continuar</button>
            </div>
        </form>
    </div>
</div>

<script>
    // Script to add a row
    $("#add_row").click(function () {
        var html = '';
        html += '<div id="row_ticket" class="row g-2 mb-2"><div class="col-4"><div class="form-floating"><select class="form-select" name="draw_list" required id="id_draw_selection"><option  value="" selected="selected">Seleccione...</option>{% for draw in draw_list %}<option value="{{ draw.pk }}">{{ draw.schedule.turn|date:"h:i A" }}</option>{% empty %}<option selected="selected">Sin Sorteos</option>{% endfor %}</select><label class="" for="id_draw_selection">Hora del sorteo</label></div></div><div class="col-4"><div class="form-floating"><select class="form-select" name="pattern_list" required id="id_pattern_selection"><option  value="" selected="selected">Seleccione...</option>{% for pattern_row in pattern_list %}<option value="{{ pattern_row.pk }}">{{ pattern_row.icon }}</option>{% endfor %}</select><label class="" for="id_pattern_selection">Ficha</label></div></div><div class="col-3"><div class="input-group"><span class="input-group-text">{{ request.user.betting_agency.get_currency_display }}</span><div class="form-floating"><input type="number" class="form-control" name="bet_amount_list" id="id_bet_amount" min="{{ request.user.betting_agency.minimum_bet }}" step=".01" required placeholder="Monto de la apuesta"><label for="id_bet_amount">Monto</label></div></div></div><div class="col-1"><button id="remove_row" type="button" class="btn mt-2"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-x-circle text-danger" viewBox="0 0 16 16"><path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/><path d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z"/></svg></button></div></div>'
        $('#new_row').append(html);
    });
    // Script to remove a row
    $(document).on('click', '#remove_row', function () {
        $(this).closest('#row_ticket').remove();
    });
</script>

{% endblock %}

templates/to_print.html
<div id="to_print">
    <h4>{{ ticket.user.betting_agency }}</h4>
    <p>{{ TAX_PREFIX }} {{ ticket.user.betting_agency.tax_id }} </p>
    <p>Ticket #{{ ticket.get_readable_uuid }}</p>
    <p>{{ ticket.get_lottery.name }}</p>
    <p>Cliente: {{ ticket.client|default:"No Aplica" }}</p>
    <p>Fecha: {{ ticket.timestamp|date:'d/m/Y' }} {{ ticket.timestamp|date:'h:i a' }}</p>
    <p>Vendedor: {{ ticket.user.get_full_name }}</p>
    <p>--------------------------------</p>
    {% for row in ticket.rowticket_set.all %}
    <p>{{ row.draw.schedule.turn|date:'h:i A' }} - {{ row.icon.name }} - {{ ticket.user.betting_agency.get_currency_display }} {{ row.bet_amount }}</p>
        {% empty %}
            <h4>Sin sorteos</h4>
    {% endfor %}
    <p>--------------------------------</p>
    <h4>Total de apuesta: {{ ticket.user.betting_agency.get_currency_display }} {{ ticket.get_total_bet_amount }}</h4>
</div>